### PR TITLE
CI: Automate release

### PR DESCRIPTION
**Pull request by zeppelin**
- Updates `ci.yaml` to make tests running on maintenance branches
- Adds `release.yml` action config
- Mirror `release-it` config with [`ember-prismic-dom`](https://github.com/qonto/ember-prismic-dom/blob/main/.github/workflows/release.yml)

### CODE REVIEW

**Comment by zeppelin** [comment]
@mrloop I can rebase today, if that's what you mean

**Comment by mrloop** [comment]
Thanks! Tried running `yarn release-it --dry-run` locally and looks OK. NPM_TOKEN now setup for this repo, going to wait till Monday morning to try first release-it release out of abundance of caution it being late on a Friday.

**Comment by mrloop** [comment]
Running `yarn` locally and `yarn.lock` is updated. Think you need to push update `yarn.lock` @zeppelin

**Comment by zeppelin** [comment]
Updated! Hope it's good now, yarn does odd things sometimes...

**Review by mrloop — APPROVED** [review]

**Pull request merged**
